# markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

default: true

# Line length - disabled (code examples can be long)
MD013: false

# Multiple headings with same content - allow for repeated sections
MD024:
  siblings_only: true

# Trailing punctuation in heading - allow ? for FAQs
MD026:
  punctuation: ".,;:!"

# Multiple top-level headings - disabled (some docs have multiple H1s)
MD025: false

# Inline HTML - allow for badges, images with attributes
MD033: false

# Bare URLs - allow (common in technical docs)
MD034: false

# First line should be top-level heading - disabled
MD041: false

# Fenced code blocks should have language specified
MD040: true

# No empty links
MD042: true

# Required heading structure - disabled (varies by doc type)
MD043: false

# Proper names should have correct capitalization - disabled (too noisy)
MD044: false

# Images should have alt text
MD045: true

# Code block style - fenced
MD046:
  style: fenced

# Files should end with single newline
MD047: true
